#:kivy 2.0
#: import SlideTransition kivy.uix.screenmanager.SlideTransition

<ReportesWid>:
    canvas:
        Color:
            rgb: .2,.2,.2
        Rectangle:
            pos: self.pos
            size: self.size
    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height

        Label:
        Label:
            text: 'Seleccione Reporte'
            font_size: '20dp'
            size_hint_y: 0.3

        Label:


        GridLayout:
            id: reportes_grid
            cols: 2
            spacing: '10dp'
            width: '390dp'
            row_default_height: '30dp'
            row_force_default: True
            pos_hint: {"center_x": 0.55}

            CheckBox:
                group: 'check_report'
                size_hint: None, 0.5
                width: '20dp'
                on_active:
                    root.checkbox_click(self, self.active, 'insumos')

            Label:
                text:'Reporte de Insumos'
                text_size: self.size
                font_size: '16dp'
                halign: 'left'
                valign: 'middle'


            CheckBox:
                group: 'check_report'
                size_hint: None, 0.5
                width: '20dp'
                on_active:
                    root.checkbox_click(self, self.active, 'ventas')

            Label:
                text:'Reporte de Ventas'
                text_size: self.size
                font_size: '16dp'
                halign: 'left'
                valign: 'middle'

        Label:

        BoxLayout:
            pos_hint: {'center_x': 0.6}

            GridLayout:
                cols: 2
                spacing: '20dp'
                width: '390dp'
                row_default_height: '38dp'
                row_force_default: True
                pos_hint: {"center_x": 0.55}

                Label:
                    text:'Mes'
                    text_size: self.size
                    size_hint: None, 0.7
                    font_size: '16dp'
                    halign: 'left'
                    valign: 'middle'

                Spinner:
                    id: ti_mes
                    text: 'Seleccione'
                    values:
                        ['Todos', 'Enero', 'Febrero', 'Marzo',\
                        'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto',\
                        'Septiembre', 'Octubre', 'Noviembre', 'Diciembre']
                    size_hint_x: None
                    width: '170dp'
                    pos_hint: {"center_x": 0.5}

                Label:
                    text:'Año'
                    text_size: self.size
                    size_hint: None, 0.7
                    font_size: '16dp'
                    halign: 'left'
                    valign: 'middle'

                Spinner:
                    id: ti_ano
                    text: 'Seleccione'
                    values:
                        ['2021', '2022', '2023',\
                        '2024', '2025', '2026', '2027',\
                        '2028', '2029', '2030']
                    size_hint_x: None
                    width: '170dp'
                    pos_hint: {"center_x": 0.5}

                Label:
                    text:''
                    text_size: self.size
                    size_hint: None, 0.7
                    font_size: '16dp'
                    halign: 'left'
                    valign: 'middle'
                Label:
                    text:''
                    text_size: self.size
                    size_hint: None, 0.7
                    font_size: '16dp'
                    halign: 'left'
                    valign: 'middle'


                Label:
                    text:'Titulo'
                    text_size: self.size
                    size_hint: None, 0.7
                    font_size: '16dp'
                    halign: 'left'
                    valign: 'middle'
                TextInput:
                    id: ti_asunto
                    size_hint_x: None
                    width: '170dp'
                    pos_hint: {"center_x": 0.5}
                    multiline: False
                    hint_text:'Ingrese un titulo'

        BoxLayout:
            size_hint_y: 6
        BoxLayout:
            Button:
                size_hint_y: None
                font_size: '14sp'
                height: '50dp'
                text: 'Salir'
                on_press: app.root.transition = SlideTransition(direction='right')
                on_release: root.mainwid.goto_start()


            Button:
                size_hint_y: None
                font_size: '14sp'
                height: '50dp'
                text:'Enviar Reporte'
                on_press: app.root.transition = SlideTransition(direction='left')
                on_release:
                    root.get_report(ti_mes.text, ti_ano.text)
                    root.mainwid.goto_reportes()